# This is a basic workflow to help you get started with Actions

name: ArmureDeSoie

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "58 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell to get current date
      - name: Set current date
        id: set-date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Runs a single command using the runners shell to increment current date
      - name: Increment date by one day
        id: increment-date
        run: |
          current_date=$(date +'%Y-%m-%d')
          incremented_date=$(date -d "$current_date + 1 day" +'%Y-%m-%d')
          echo "INCREMENTED_DATE=$incremented_date" >> $GITHUB_ENV
          
      # Runs a single command using the runners shell to curl loadOffers for that day
      - name: Run a one-line script
        run: curl -X GET "https://09ji8m4ho6.execute-api.us-west-1.amazonaws.com/prod/api/loadOffers/${{ env.CURRENT_DATE }}"
